language: python
python:
  - "3.9"

services:
  - docker

jobs:
  include:
    - stage: create_rpm
      script:
        - docker run --rm -v $PWD:/workspace -w /workspace oraclelinux:8 bash -c "mkdir -p test && yum install -y rpm-build wget && wget https://raw.githubusercontent.com/EvgeniyPatlan/sorting-library/refs/heads/main/packaging/script/builder.sh && chmod +x builder.sh && ./builder.sh --install_deps=1 --get_sources=1 --builddir=/workspace/test --build_src_rpm=1 --build_rpm=1".
      artifacts:
        paths:
          - rpm/*.rpm

    - stage: create_deb
      script:
        - wget https://raw.githubusercontent.com/EvgeniyPatlan/sorting-library/refs/heads/main/packaging/script/builder.sh
        - chmod +x builder.sh
        - mkdir -p /tmp/SORTING_LIB
        - sudo ./builder.sh --builddir=/tmp/SORTING_LIB --install_deps=1
        - ./builder.sh --builddir=/tmp/SORTING_LIB --get_sources=1 --build_source_deb=1 --build_deb=1
      artifacts:
        paths:
          - deb/*.deb
