name: Build RPM, DEB, and Docker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  create_source_tarball:
    runs-on: ubuntu-latest

    steps:
    - name: Download builder script
      run: |
        wget https://raw.githubusercontent.com/EvgeniyPatlan/sorting-library/refs/heads/main/packaging/script/builder.sh -O builder.sh
    - name: Upload builder script
      uses: actions/upload-artifact@v4
      with:
        name: builder-script
        path: builder.sh

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Download builder script
      uses: actions/download-artifact@v4
      with:
        name: builder-script
    - name: Install build dependencies
      run: |
        chmod +x $GITHUB_WORKSPACE/builder.sh
        mkdir -p /tmp/SORTING_LIB
        sudo $GITHUB_WORKSPACE/builder.sh --builddir=/tmp/SORTING_LIB --install_deps=1

    - name: Create Source Tarball
      run: |
        mkdir -p /tmp/SORTING_LIB
        ./builder.sh --builddir=/tmp/SORTING_LIB --get_sources=1

    - name: Upload Source Tarball
      uses: actions/upload-artifact@v4
      with:
        name: sorting-library-source-tarball
        path: /tmp/SORTING_LIB/source_tarball/*.tar.gz

  create_source_rpm:
    needs: create_source_tarball
    runs-on: rockylinux-latest

    steps:
    - name: Download Source Tarball
      uses: actions/download-artifact@v4
      with:
        name: sorting-library-source-tarball

    - name: Move Source Tarball to source_tarball directory
      run: |
        mkdir -p source_tarball
        mv *.tar.gz source_tarball/

    - name: Download builder script
      uses: actions/download-artifact@v4
      with:
        name: builder-script
    - name: Install build dependencies
      run: |
        chmod +x $GITHUB_WORKSPACE/builder.sh
        mkdir -p /tmp/SORTING_LIB
        sudo $GITHUB_WORKSPACE/builder.sh --builddir=/tmp/SORTING_LIB --install_deps=1

    - name: Create Source RPM
      run: |
        mkdir -p /tmp/SORTING_LIB
        ./builder.sh --builddir=/tmp/SORTING_LIB --build_src_rpm=1

    - name: Upload Source RPM
      uses: actions/upload-artifact@v4
      with:
        name: sorting-library-source-rpm
        path: "srpm/*.src.rpm"

  create_source_deb:
    needs: create_source_tarball
    runs-on: ubuntu-22.04

    steps:
    - name: Download Source Tarball
      uses: actions/download-artifact@v4
      with:
        name: sorting-library-source-tarball

    - name: Move Source Tarball to source_tarball directory
      run: |
        mkdir -p source_tarball
        mv *.tar.gz source_tarball/

    - name: Download builder script
      uses: actions/download-artifact@v4
      with:
        name: builder-script
    - name: Install build dependencies
      run: |
        chmod +x $GITHUB_WORKSPACE/builder.sh
        mkdir -p /tmp/SORTING_LIB
        sudo $GITHUB_WORKSPACE/builder.sh --builddir=/tmp/SORTING_LIB --install_deps=1

    - name: Create Source DEB
      run: |
        mkdir -p /tmp/SORTING_LIB
        ./builder.sh --builddir=/tmp/SORTING_LIB --build_source_deb=1

    - name: Upload Source DEB
      uses: actions/upload-artifact@v4
      with:
        name: sorting-library-source-deb
        path: "source_deb/*.dsc, source_deb/*.tar.gz, source_deb/*.changes, source_deb/*.diff.gz"

  build_rpm:
    needs: create_source_rpm
    runs-on: rockylinux-latest

    steps:
    - name: Create RPM directory
      run: mkdir -p rpm

    - name: Download Source RPM
      uses: actions/download-artifact@v4
      with:
        name: sorting-library-source-rpm

    - name: Move Source RPM to srpm directory
      run: |
        mkdir -p srpm
        mv *.src.rpm srpm/

    - name: Install build dependencies
      run: |
        chmod +x $GITHUB_WORKSPACE/builder.sh
        mkdir -p /tmp/SORTING_LIB
        sudo $GITHUB_WORKSPACE/builder.sh --builddir=/tmp/SORTING_LIB --install_deps=1

    - name: Build RPM
      run: |
        mkdir -p /tmp/SORTING_LIB
        chmod +x $GITHUB_WORKSPACE/builder.sh
        ./builder.sh --builddir=/tmp/SORTING_LIB --build_rpm=1 && mv /tmp/SORTING_LIB/rpm/*.rpm rpm/

    - name: Upload RPM Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sorting-library-rpm
        path: "rpm/*.rpm"

  build_deb:
    needs: create_source_deb
    runs-on: ubuntu-24.04

    steps:
    - name: Create DEB directory
      run: mkdir -p deb

    - name: Download Source DEB
      uses: actions/download-artifact@v4
      with:
        name: sorting-library-source-deb

    - name: Move Source DEB to source_deb directory
      run: |
        mkdir -p source_deb
        mv *.dsc *.tar.gz *.changes *.diff.gz source_deb/

    - name: Install build dependencies
      run: |
        ./builder.sh --install_deps=1

    - name: Build DEB
      run: |
        mkdir -p /tmp/SORTING_LIB
        chmod +x $GITHUB_WORKSPACE/builder.sh
        ./builder.sh --builddir=/tmp/SORTING_LIB --build_deb=1 && mv /tmp/SORTING_LIB/deb/*.deb deb/

    - name: Upload DEB Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: sorting-library-deb
        path: "deb/*.deb"

  build_docker:
    needs: [build_rpm, build_deb]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download RPM and DEB Artifacts
      uses: actions/download-artifact@v4
      with:
        name: sorting-library-rpm
    - name: Download DEB Artifacts
      uses: actions/download-artifact@v4
      with:
        name: sorting-library-deb

    - name: Build Docker Image
      run: |
        docker build -t sorting-library .

    - name: Save Docker Image as File
      run: |
        docker save sorting-library -o sorting-library.tar

    - name: Upload Docker Image
      uses: actions/upload-artifact@v4
      with:
        name: sorting-library-docker
        path: sorting-library.tar

  scan_docker:
    needs: build_docker
    runs-on: ubuntu-latest

    steps:
    - name: Download Docker Image
      uses: actions/download-artifact@v4
      with:
        name: sorting-library-docker

    - name: Load Docker Image
      run: |
        docker load -i sorting-library.tar

    - name: Install Trivy
      run: |
        curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh

    - name: Scan Docker Image for CVEs
      run: |
        ./trivy image sorting-library